language: python
python:
  - "3.5"
  - "3.6"
cache:
  directories:
    - $HOME/.cache/pip
    - node_modules
sudo: required
services:
  - postgresql
addons:
  postgresql: "9.6"
  firefox: "56.0"
  apt:
    packages:
      - postgresql-9.6-postgis-2.3

before_install:
  - pip install coveralls flake8 coverage beautifulsoup4 py-dateutil pytz
  - pip install selenium cryptography jwt redis
  - gem install coveralls-lcov

before_script:
  - bash install-postgres-10.sh
  - python3 -m flake8 .
  - psql -c 'create database doko;' -U postgres
  - head -c 24 /dev/urandom > cookie_secret
  - nvm install 8.9.0
  - npm install npm -g
  - npm install
  - npm install create-react-class
  - node_modules/gulp/bin/gulp.js dev-build
  - ./tests/python/selenium_webapp.py &>/dev/null &
  - sleep 2

script:
  - npm test
  - xvfb-run --server-args="-screen 0, 1280x1280x16" tests/python/coverage_run.sh

after_success:
  - coveralls-lcov -v -n coverage/lcov.info > coverage.json
  - coveralls --merge=coverage.json

notifications:
  email:
    on_failure: change
